baseURL = 'https://oss.anchore.com/'
languageCode = 'en-us'
title = 'OSS Documentation'
publishDir = "public/"
theme = "docsy"

# ignoreLogs setting because we have some raw html
# snippets, which cause warnings we don't need
# https://discourse.gohugo.io/t/ignorelogs-warning-goldmark-raw-html/52469
ignoreLogs = ['warning-goldmark-raw-html']

# enableGitInfo Enables bar on right of screen,
# for fast access to GitHub docs repo for easier
# contributions
enableGitInfo = true

[menus]
  # Items on the top-right of the header
  [[menus.main]]
    name = "OSS Docs"
    weight = -102
    pre = "<i class='fas fa-book pr-2'></i>"
    url = "/"
  [[menus.main]]
    name = "Enterprise Docs"
    weight = -101
    pre = "<i class='fas fa-book pr-2'></i>"
    url = "https://docs.anchore.com/current/"
  [[menus.main]]
    name = "Events"
    weight = -100
    pre = "<i class='fas fa-calendar pr-2'></i>"
    url = "/docs/about/events/"
  [[menus.main]]
    name = "Blog"
    weight = -99
    pre = "<i class='fas fa-rss pr-2'></i>"
    url = "https://anchore.com/blog/"
  [[menus.main]]
    name = "GitHub"
    weight = -98
    pre = "<i class='fab fa-github pr-2'></i>"
    url = "https://github.com/anchore/"
  [[menus.main]]
    name = "Discourse"
    weight = -97
    pre = "<i class='fab fa-discourse pr-2'></i>"
    url = "https://anchore.com/discourse"

[sitemap]
  changeFreq = ''
  filename = 'sitemap.xml'
  priority = -1

[params]
  description = "Anchore Open Source Documentation for SBOM creation and vulnerability detection"
  copyright = "Anchore Inc"
  privacy_policy = "https://anchore.com/privacy"
  environment = "development"
  custom_css = ["css/custom.css"]
  github_repo = "https://github.com/anchore/oss-docs"
  github_project_repo = "https://github.com/anchore/oss-docs"

[params.links]
    # Links which appear on the left of the footer
    [[params.links.user]]
        name = "OSS Docs home"
        url = "https://oss.anchore.com/"
        icon = "fas fa-home"
        desc = "Anchore OSS Docs Site"
    [[params.links.user]]
        name = "Anchore, Inc."
        url = "https://anchore.com"
        icon = "fas fa-university"
        desc = "Anchore Company Site"

    # Links which appear on the right of the footer
    [[params.links.developer]]
        name = "Twitter/X"
        url = "https://x.com/anchore"
        icon = "fab fa-x-twitter"
        desc = "Follow Anchore on Twitter/X"
    [[params.links.developer]]
        name = "Mastodon"
        url = "https://mstdn.business/@anchore"
        icon = "fab fa-mastodon pr-2"
        desc = "Follow Anchore on Mastodon"
    [[params.links.developer]]
        name = "BlueSky"
        url = "https://bsky.app/profile/anchore.com"
        icon = "fab fa-bluesky pr-2"
        desc = "Follow Anchore on BlueSky"
    [[params.links.developer]]
        name = "Discourse"
        url = "https://anchore.com/discourse"
        icon = "fab fa-discourse"
        desc = "Discuss with developers on our Discourse"
    [[params.links.developer]]
        name = "GitHub"
        url = "https://github.com/anchore"
        icon = "fab fa-square-github"
        desc = "Browse and contribute on GitHub!"

[params.ui]
  # Enable to show the side bar menu in its compact state.
  sidebar_menu_compact = true
  # Set to true to disable breadcrumb navigation.
  breadcrumb_disable = false
  sidebar_search_disable = false
  navbar_translucent_over_cover_disable = true

  # Custom logo configuration
  navbar_logo = true

  # Optimize font loading
  preload_fonts = ["Poppins:400,500,600"]

  # Commented this out, because some of the styling in dark mode
  # needs fixing.
  showLightDarkModeMenu = true

  # We don't want all the release notes for every release to
  # appear in the left-hand menu. Only the first 10 is enough.
  sidebar_menu_truncate = 10

[params.ui.feedback]
  # Feedback disabled unless we can find value in it. It seeems a bit in your face to me.
  # Adds a H2 section titled "Feedback" to the bottom of each doc. The responses are sent to Google Analytics as events.
  # This feature depends on [services.googleAnalytics] and will be disabled if "services.googleAnalytics.id" is not set.
  # If you want this feature, but occasionally need to remove the "Feedback" section from a single page,
  # add "hide_feedback: true" to the page's front matter.
  # enable = true
  # The responses that the user sees after clicking "yes" (the page was helpful) or "no" (the page was not helpful).
  yes = 'Glad to hear it! Please <a href="https://github.com/anchore/oss-docs-preview/issues/new">tell us how we can improve</a>.'
  no = 'Sorry to hear that. Please <a href="https://github.com/anchore/oss-docs-preview/issues/new">tell us how we can improve</a>.'

[params.print]
disable_toc = true

[outputs]
  home = ["HTML"]
  page = ["HTML"]
  section = ["HTML", "RSS", "print"]

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    tabWidth = 4

    # see https://gohugo.io/content-management/syntax-highlighting/
    # we generate these with "hugo gen chromastyles --style=github > assets/scss/_chroma-github.scss"

     # this will honor the "style" configuration (which does not respond to light/dark mode)
    noClasses = true

    # this will IGNORE the style configuration, has an import in _styles_project.scss, but honors the light/dark mode
    # note: there seems to be a problem with the default font on light mode though, so we'll stick with noClasses = true for now
    # noClasses = false

    style = "dracula"

  [markup.goldmark.renderer]
    unsafe = true


  [markup.goldmark.parser]
    [markup.goldmark.parser.attribute]
      block = true
