#!/usr/bin/env python3
"""
Configuration constants and defaults for documentation generation scripts.

Provides centralized configuration via dataclasses to ensure
consistent paths, images, and settings across all scripts.
"""

from dataclasses import dataclass
from pathlib import Path


def _get_project_root() -> Path:
    """get the project root directory (parent of scripts/)."""
    return Path(__file__).parent.parent.parent


@dataclass(frozen=True)
class Paths:
    """file system paths used across scripts."""

    # project root directory
    project_root: Path = _get_project_root()

    # data directories (input)
    data_dir: Path = project_root / "data"
    sbom_data_dir: Path = data_dir / "sbom"
    template_examples_dir: Path = sbom_data_dir / "template-examples"
    jq_query_examples_dir: Path = sbom_data_dir / "jq-query-examples"
    capabilities_data_dir: Path = data_dir / "capabilities"
    reference_cache_dir: Path = data_dir  # cache for reference doc generation

    # data files
    format_versions_json: Path = sbom_data_dir / "format-versions.json"
    cataloger_cache_file: Path = capabilities_data_dir / "syft-package-catalogers.json"
    ecosystem_aliases_file: Path = capabilities_data_dir / "ecosystem.yaml"
    os_data_file: Path = capabilities_data_dir / "grype-operating-systems.json"
    vulnerability_data_file: Path = capabilities_data_dir / "vulnerability-data.yaml"

    # content directories (output)
    content_dir: Path = project_root / "content"
    docs_dir: Path = content_dir / "docs"
    user_guides_dir: Path = docs_dir / "guides"
    sbom_guides_dir: Path = user_guides_dir / "sbom"
    snippets_dir: Path = sbom_guides_dir / "snippets"

    # snippet subdirectories
    templates_snippet_dir: Path = snippets_dir / "templates"
    jq_queries_snippet_dir: Path = snippets_dir / "jq-queries"
    format_snippet_dir: Path = snippets_dir / "format"
    format_examples_snippet_dir: Path = format_snippet_dir / "examples"
    capabilities_snippet_dir: Path = docs_dir / "capabilities" / "snippets"

    # snippet files
    format_versions_snippet: Path = format_snippet_dir / "versions.md"


@dataclass(frozen=True)
class DockerImages:
    """docker image references used across scripts."""

    # syft image for running scans
    syft: str = "anchore/syft:latest"

    # test images for generating examples
    alpine_test: str = "alpine:3.9.2"
    busybox_test: str = "busybox:latest"


@dataclass(frozen=True)
class Timeouts:
    """timeout values in seconds for various operations."""

    # syft operations
    syft_scan_default: int = 60
    syft_scan_with_config: int = 120
    syft_format_version_check: int = 60
    cataloger_info: int = 60

    # jq operations
    jq_query: int = 30

    # docker operations
    docker_command: int = 10


def get_generated_comment(script_path: str, format_type: str = "html") -> str:
    """
    generate an auto-generated comment for the specified format type.

    args:
        script_path: relative path to the script that generates the file
        format_type: one of "html", "yaml", or "json"

    returns:
        formatted comment string with trailing newlines
    """
    message = f"AUTO-GENERATED by {script_path} -- DO NOT MANUALLY EDIT"

    if format_type == "html":
        return f"<!-- {message} -->\n\n"
    elif format_type == "yaml":
        return f"# {message}\n\n"
    elif format_type == "json":
        # JSON doesn't support comments, return a field name/value pair
        return message
    else:
        raise ValueError(f"Unsupported format type: {format_type}")


# singleton instances for easy import
paths = Paths()
docker_images = DockerImages()
timeouts = Timeouts()
