#!/bin/bash

# This script generates a markdown file in content/community/adopters.md 
# with the list of GitHub orgs/repositories that consume on a given OSS project.
# It uses the `github-dependents-info` python tool to gather this information.

# We build the markdown page in a temporary directory, and then move it to the correct location.
# The script also creates a new git branch for the changes, commits them, and provides instructions for further actions.

# Usage: ./scripts/generate-adopters-info.sh
# See also ./scripts/README.md for more details.

## Variables

# We do not want to include repos with less than this many stars
minstars=50
datestamp="$(date +%Y-%m-%d_%H-%M-%S)"
tmpdir="$(mktemp -d)"
tmpadoptersfile="$tmpdir/adopters-page.md"

## Pre-flight checks

# Ensure we have a virtual environment set up
if [ ! -d ".venv" ]; then
    echo "Missing virtual environment..."
    echo "Use 'python3 -m venv .venv' or 'uv venv --python 3.12' to create a virtual environment."
    exit 1
fi

# Activate the virtual environment
if ! source .venv/bin/activate; then 
    echo "Failed to activate the virtual environment. Exiting."
    exit 1
fi

# Make sure we have github-dependents-info installed
if ! command -v github-dependents-info &> /dev/null; then
    echo "github-dependents-info is not installed. Please install it using 'pip install github-dependents-info'."
    exit 1
fi

# # Create a branch for the changes
# if ! git checkout -b "update-adopters-page-$datestamp"; then
#     echo "Failed to create or switch to the branch. Exiting."
#     exit 1
# fi

# Create the front-matter for the adopters hugo page
cat << EOF >> "$tmpadoptersfile"
+++
title =  "OSS Adopters"
description = "Adopters of Anchore Open Source Tools"
weight = 20
categories = ["community"]
url = "docs/about/adopters"
+++

[//]: # (Content generated by github-dependents-info in scripts/generate-adopters-info.sh)

Our tools are used by organisations and developer teams of all sizes. Below is a small sample of users of our tools, in public GitHub repositories.

{{< adopters-list >}}


EOF

for repo in syft grype scan-action sbom-action; do
    echo $repo
    markdownfile="/$tmpdir/$datestamp-$repo-adopters.md"
    if ! github-dependents-info --repo anchore/"$repo" --markdownfile "$markdownfile" --minstars "$minstars" --sort stars --mergepackages --verbose; then
        echo "❌ Error generating adopters info for $repo. Exiting."
        exit 1
    fi
    echo "✅ Successfully generated adopters info for $repo"
done

cat << EOF >> "$tmpadoptersfile"

More organisations below are all adopters of our tools, in public GitHub repositories.

{{% cardpane %}} 
{{% card  title="Syft" %}}

EOF

grep "^|" /"$tmpdir"/"$datestamp"-syft-adopters.md >> "$tmpadoptersfile"

cat << EOF >> "$tmpadoptersfile"
{{% /card %}}
{{% card  title="Grype" %}}

EOF
grep "^|" /"$tmpdir"/"$datestamp"-grype-adopters.md >> "$tmpadoptersfile"

cat << EOF >> "$tmpadoptersfile"

{{% /card %}}
{{% /cardpane %}}

{{% cardpane %}} 
{{% card  title="SBOM Action" %}}

EOF

grep "^|" /"$tmpdir"/"$datestamp"-sbom-action-adopters.md >> "$tmpadoptersfile"
cat << EOF >> "$tmpadoptersfile"

{{% /card %}}
{{% card  title="Scan Action" %}}

EOF

grep "^|" /"$tmpdir"/"$datestamp"-scan-action-adopters.md >> "$tmpadoptersfile"
cat << EOF >> "$tmpadoptersfile"
{{% /card %}}
{{% /cardpane %}}

_Generated using [github-dependents-info](https://github.com/nvuillam/github-dependents-info), by [Nicolas Vuillamy](https://github.com/nvuillam)_"
EOF

echo "$tmpadoptersfile"

# Move the generated file to the correct location
mv "$tmpadoptersfile" content/about/adopters.md

# # Add the changes to git
# if ! git add content/oss/about/adopters.md; then
#     echo "Failed to add changes to git. Exiting."
#     exit 1
# fi

# # Commit the changes
# if ! git commit -m "Update adopters page with latest data"; then 
#     echo "Failed to commit changes. Exiting."
#     exit 1
# fi
# echo "All adopters info has been generated and committed!"